# Generated by Django 3.1.3 on 2020-12-05 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0003_auto_20201204_2106'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artigo.produto'),
        ),
    ]
