# Generated by Django 3.1.3 on 2020-11-13 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usr', models.CharField(choices=[('Atleta', 'Atleta'), ('Treinador', 'Treinador')], default='Atleta', max_length=9)),
                ('qtd', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user_takeout', models.BooleanField(default=False)),
                ('tipo_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artigo.tipodeproduto')),
            ],
            options={
                'verbose_name_plural': 'Aluguéis',
            },
        ),
    ]
