# Generated by Django 3.1.3 on 2020-12-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigo', '0004_auto_20201205_0038'),
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='user_takeout',
            new_name='rented',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='tipo_prod',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='tipo_usr',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artigo.produto'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='rented_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='user_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
