# Generated by Django 3.1.3 on 2020-11-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluguel',
            new_name='Aluguei',
        ),
        migrations.RenameModel(
            old_name='ItemDeAluguel',
            new_name='ItensDeAluguei',
        ),
    ]
