# Generated by Django 3.1.3 on 2020-11-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_auto_20201107_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluguei',
            new_name='Aluguel',
        ),
        migrations.RenameModel(
            old_name='ItensDeAluguei',
            new_name='ItemDeAluguel',
        ),
    ]
