# Generated by Django 3.1.3 on 2020-12-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_auto_20201207_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='rented',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
