# Generated by Django 3.1.3 on 2020-12-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_auto_20201208_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluguel',
            old_name='disponivel',
            new_name='not_rented',
        ),
    ]
