# Generated by Django 3.1.3 on 2020-12-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0005_auto_20201209_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
