# Generated by Django 3.1.3 on 2020-11-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0006_auto_20201107_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='tipo_usr',
            field=models.CharField(choices=[('Atleta', 'Atleta'), ('Treinador', 'Treinador')], default='Atleta', max_length=9),
        ),
    ]
