# Generated by Django 3.1.3 on 2020-12-09 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0006_auto_20201209_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 3, 41, 23, 131439)),
        ),
    ]
