# Generated by Django 3.1.3 on 2020-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0009_auto_20201209_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
