# Generated by Django 3.1.3 on 2020-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0010_auto_20201209_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='user_returned',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='rent_in_process',
            field=models.BooleanField(default=True),
        ),
    ]
