# Generated by Django 3.1.3 on 2020-11-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('esporte', models.CharField(max_length=100)),
                ('qtd_disp', models.IntegerField()),
                ('qtd_alug', models.IntegerField()),
                ('qtd_rese', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='C:\\Users\\fefep\\Desktop\\POLI 2020.2\\PMR3304 - Sistemas de informação\\cepeguel/fotos/fotosdeartigo')),
                ('disp', models.BooleanField()),
                ('alug', models.BooleanField()),
                ('rese', models.BooleanField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artigo.tipodeproduto')),
            ],
        ),
    ]
