# Generated by Django 3.1.3 on 2020-12-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modalidade', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='artigo.modalidade')),
            ],
            options={
                'verbose_name_plural': 'Tipos de produtos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='C:\\dev\\cepeguel/fotos/fotosdeartigo')),
                ('disp', models.BooleanField()),
                ('alug', models.BooleanField()),
                ('rese', models.BooleanField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artigo.tipodeproduto')),
            ],
        ),
    ]
