# Generated by Django 3.1.3 on 2020-12-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
