# Generated by Django 3.1.3 on 2020-11-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(upload_to='C:\\Users\\lucas\\cepeguel/fotos/fotosdeartigo'),
        ),
    ]
