# Generated by Django 3.1.3 on 2020-12-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0002_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(upload_to='C:\\Users\\ticto\\cepeguel/fotos/fotosdeartigo'),
        ),
    ]
