# Generated by Django 3.1.3 on 2020-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0003_auto_20201106_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tipodeproduto',
            options={'verbose_name_plural': 'Tipos de produtos'},
        ),
    ]
