# Generated by Django 3.1.3 on 2020-11-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0004_auto_20201107_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artigo',
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
    ]
